# Generated by Django 5.1.6 on 2025-03-20 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dependency',
        ),
        migrations.AlterField(
            model_name='project',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependencies.dependency', verbose_name='Dependencia Solicitante'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
