# Generated by Django 5.1.6 on 2025-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Dependencia')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('responsible', models.CharField(max_length=200, verbose_name='Responsable')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo del Responsable')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['name'],
            },
        ),
    ]
